"""Index generation for Marvin.

Generates .index.yaml with task counts and metadata for efficient LLM navigation.
"""

from datetime import datetime
from pathlib import Path
from typing import Any

import yaml

from marvin.task_schema import load_task_file


def parse_task_file(file_path: Path) -> dict[str, Any]:
    """Parse a task JSON file and extract metadata.
    
    Returns:
        dict with task_count, open_count, waiting_count, overdue_count, next_deadline
    """
    try:
        tf = load_task_file(file_path)
    except Exception:
        # Return empty stats for invalid files
        return {
            'task_count': 0,
            'open_count': 0,
            'waiting_count': 0,
            'overdue_count': 0,
            'next_deadline': None,
        }
    
    return {
        'task_count': len(tf.tasks),
        'open_count': tf.open_count,
        'waiting_count': tf.waiting_count,
        'overdue_count': tf.overdue_count,
        'next_deadline': tf.next_deadline.isoformat() if tf.next_deadline else None,
    }


def rebuild_index(data_dir: Path) -> None:
    """Rebuild .index.yaml from the task and idea files.
    
    Args:
        data_dir: Path to the data directory (e.g., ~/.marvin/data)
    """
    tasks_path = data_dir / 'tasks.json'
    
    # Parse tasks
    if tasks_path.exists():
        stats = parse_task_file(tasks_path)
    else:
        stats = {
            'task_count': 0,
            'open_count': 0,
            'waiting_count': 0,
            'overdue_count': 0,
            'next_deadline': None,
        }
    
    # Parse ideas
    ideas_path = data_dir / 'ideas.json'
    idea_stats: dict[str, Any] = {
        'total': 0,
        'sparks': 0,
        'developing': 0,
        'mature': 0,
        'archived': 0,
        'expiring_soon': 0,
    }
    if ideas_path.exists():
        try:
            from marvin.idea_schema import load_idea_file
            idea_file = load_idea_file(ideas_path)
            idea_stats['total'] = len(idea_file.active_ideas)
            idea_stats['sparks'] = len(idea_file.sparks)
            idea_stats['developing'] = len(idea_file.developing_ideas)
            idea_stats['mature'] = len(idea_file.mature_ideas)
            idea_stats['archived'] = len(
                [i for i in idea_file.ideas if i.status == "archived"]
            )
            idea_stats['expiring_soon'] = len(idea_file.expiring_ideas())
        except Exception:
            pass
    
    # Build index
    index = {
        'generated_at': datetime.now().isoformat(),
        'tasks': stats,
        'ideas': idea_stats,
    }
    
    # Write index file
    index_path = data_dir / '.index.yaml'
    with open(index_path, 'w') as f:
        f.write('# Auto-generated by Marvin. DO NOT EDIT.\n')
        yaml.dump(index, f, default_flow_style=False, sort_keys=False)
