"""Index generation for lab-agent.

Generates .index.yaml with task counts and metadata for efficient LLM navigation.
"""

from datetime import datetime
from pathlib import Path
from typing import Any

import yaml

from lab_agent.task_schema import load_task_file


def parse_task_file(file_path: Path) -> dict[str, Any]:
    """Parse a task JSON file and extract metadata.
    
    Returns:
        dict with task_count, open_count, waiting_count, overdue_count, next_deadline
    """
    try:
        tf = load_task_file(file_path)
    except Exception:
        # Return empty stats for invalid files
        return {
            'task_count': 0,
            'open_count': 0,
            'waiting_count': 0,
            'overdue_count': 0,
            'next_deadline': None,
        }
    
    return {
        'task_count': len(tf.tasks),
        'open_count': tf.open_count,
        'waiting_count': tf.waiting_count,
        'overdue_count': tf.overdue_count,
        'next_deadline': tf.next_deadline.isoformat() if tf.next_deadline else None,
    }


def rebuild_index(data_dir: Path) -> None:
    """Rebuild .index.yaml from the task file.
    
    Args:
        data_dir: Path to the data directory (e.g., ~/.lab-agent/data)
    """
    tasks_path = data_dir / 'tasks.json'
    
    # Parse tasks
    if tasks_path.exists():
        stats = parse_task_file(tasks_path)
    else:
        stats = {
            'task_count': 0,
            'open_count': 0,
            'waiting_count': 0,
            'overdue_count': 0,
            'next_deadline': None,
        }
    
    # Build index
    index = {
        'generated_at': datetime.now().isoformat(),
        'tasks': stats,
    }
    
    # Write index file
    index_path = data_dir / '.index.yaml'
    with open(index_path, 'w') as f:
        f.write('# Auto-generated by lab-agent. DO NOT EDIT.\n')
        yaml.dump(index, f, default_flow_style=False, sort_keys=False)
