"""Index generation for lab-agent.

Generates .index.yaml with task counts and metadata for efficient LLM navigation.
"""

import re
from datetime import datetime, date
from pathlib import Path
from typing import Any

import yaml


def parse_task_file(file_path: Path) -> dict[str, Any]:
    """Parse a task file and extract metadata.
    
    Returns:
        dict with task_count, open_count, waiting_count, overdue_count, next_deadline
    """
    content = file_path.read_text()
    
    # Count tasks
    open_tasks = len(re.findall(r'^- \[ \]', content, re.MULTILINE))
    completed_tasks = len(re.findall(r'^- \[x\]', content, re.MULTILINE | re.IGNORECASE))
    waiting_count = len(re.findall(r'@waiting\([^)]+\)', content))
    
    # Find deadlines
    deadline_pattern = r'@deadline\((\d{4}-\d{2}-\d{2})\)'
    deadlines = re.findall(deadline_pattern, content)
    
    today = date.today()
    overdue_count = 0
    next_deadline = None
    
    for d in deadlines:
        try:
            deadline_date = datetime.strptime(d, '%Y-%m-%d').date()
            if deadline_date < today:
                overdue_count += 1
            elif next_deadline is None or deadline_date < next_deadline:
                next_deadline = deadline_date
        except ValueError:
            pass
    
    # Extract priority from frontmatter
    priority = 'medium'
    frontmatter_match = re.match(r'^---\n(.+?)\n---', content, re.DOTALL)
    if frontmatter_match:
        try:
            fm = yaml.safe_load(frontmatter_match.group(1))
            if isinstance(fm, dict):
                priority = fm.get('priority', 'medium')
        except yaml.YAMLError:
            pass
    
    return {
        'task_count': open_tasks + completed_tasks,
        'open_count': open_tasks,
        'waiting_count': waiting_count,
        'overdue_count': overdue_count,
        'next_deadline': next_deadline.isoformat() if next_deadline else None,
        'priority': priority,
    }


def rebuild_index(data_dir: Path) -> None:
    """Rebuild .index.yaml from all task files.
    
    Args:
        data_dir: Path to the data directory (e.g., ~/.lab-agent/data)
    """
    projects = []
    
    # Scan projects directory
    projects_dir = data_dir / 'projects'
    if projects_dir.exists():
        for tasks_file in projects_dir.rglob('tasks.md'):
            rel_path = tasks_file.relative_to(data_dir)
            project_name = str(rel_path.parent.relative_to('projects'))
            
            stats = parse_task_file(tasks_file)
            projects.append({
                'name': project_name,
                'path': str(rel_path),
                **stats,
            })
    
    # Sort by priority (high > medium > low), then by next_deadline
    priority_order = {'high': 0, 'medium': 1, 'low': 2}
    projects.sort(key=lambda p: (
        priority_order.get(p.get('priority', 'medium'), 1),
        p.get('next_deadline') or '9999-99-99',
    ))
    
    # Parse inbox
    inbox_stats = {'task_count': 0, 'open_count': 0}
    inbox_path = data_dir / 'inbox.md'
    if inbox_path.exists():
        stats = parse_task_file(inbox_path)
        inbox_stats = {
            'task_count': stats['task_count'],
            'open_count': stats['open_count'],
        }
    
    # Build index
    index = {
        'generated_at': datetime.now().isoformat(),
        'projects': projects,
        'inbox': inbox_stats,
    }
    
    # Write index file
    index_path = data_dir / '.index.yaml'
    with open(index_path, 'w') as f:
        f.write('# Auto-generated by lab-agent. DO NOT EDIT.\n')
        yaml.dump(index, f, default_flow_style=False, sort_keys=False)
